In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
df=pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue','Red', 'Green', 'Green', 'Red', 'Blue']
    })
df.head()

   Color
0    Red
1   Blue
2  Green
3    Red
4   Blue

In [8]:
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[['Color']]).toarray()

In [9]:
encoded_df=pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['Color']))

In [10]:
encoded_df.head()

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [11]:
encoder.transform([['Red'], ['Blue'], ['Green']]).toarray()

c:\Users\faith\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [12]:
pd.concat([df, encoded_df], axis=1)

   Color  Color_Blue  Color_Green  Color_Red
0    Red         0.0          0.0        1.0
1   Blue         1.0          0.0        0.0
2  Green         0.0          1.0        0.0
3    Red         0.0          0.0        1.0
4   Blue         1.0          0.0        0.0
5    Red         0.0          0.0        1.0
6  Green         0.0          1.0        0.0
7  Green         0.0          1.0        0.0
8    Red         0.0          0.0        1.0
9   Blue         1.0          0.0        0.0

In [14]:
import seaborn as sns
df=sns.load_dataset('tips')

In [15]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [20]:
encoded_tips_df=encoder.fit_transform(df[['sex']]).toarray()
encoded_df=pd.DataFrame(encoded_tips_df, columns=encoder.get_feature_names_out(['sex']))

In [21]:
encoded_df.head()

   sex_Female  sex_Male
0         1.0       0.0
1         0.0       1.0
2         0.0       1.0
3         0.0       1.0
4         1.0       0.0

In [22]:
final_df=pd.concat([encoded_df,df],axis=1)

In [23]:
final_df.head()

   sex_Female  sex_Male  total_bill   tip     sex smoker  day    time  size
0         1.0       0.0       16.99  1.01  Female     No  Sun  Dinner     2
1         0.0       1.0       10.34  1.66    Male     No  Sun  Dinner     3
2         0.0       1.0       21.01  3.50    Male     No  Sun  Dinner     3
3         0.0       1.0       23.68  3.31    Male     No  Sun  Dinner     2
4         1.0       0.0       24.59  3.61  Female     No  Sun  Dinner     4