In [1]:
import pandas as pd
#loading external data into dataframe
df=pd.read_csv('nyc_weather.csv')
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [84]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [85]:
#Accessing data from dataframe.
df['Temperature'].head(10)

0    38
1    36
2    40
3    25
4    20
5    33
6    39
7    39
8    44
9    50
Name: Temperature, dtype: int64

In [86]:
df.iloc[0][1]

C:\Users\faith\AppData\Local\Temp\ipykernel_13468\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(38)

In [87]:
#Accessing a specfied 
df.at[1,'Temperature']

np.int64(36)

In [88]:
df.iat[2,2]

np.int64(21)

In [89]:
df['Temperature'].max()

50

In [90]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [91]:
df['WindSpeedMPH'].mean()

np.float64(6.892857142857143)

In [92]:
#Data manipulation
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [93]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [94]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [95]:
#Handling missing data
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [100]:
df.dropna(subset=['Events'], inplace=True)

In [101]:
df.isnull().sum()

EST                     0
Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            2
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [102]:
df_filled=df.fillna(0)
df_filled.isnull().sum()

EST                     0
Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [103]:
# Change the data type
df_filled.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [106]:
#Renaming columns
df=df_filled.rename(columns={'EST':'Date'})
df.head()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293

In [110]:
df['Sea Level PressureInches']=df['Sea Level PressureIn'].astype(int)

In [114]:
df.head(5)

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,Sea Level PressureInches
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76,30
9,1/10/2016,50,46,71,29.59,4,0.0,1.8,7,Rain,109,29
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340,29
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345,29
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293,29

In [113]:
grouped_mean=df.groupby('Events')['Temperature'].mean()
print(grouped_mean)

Events
Fog-Snow    31.000000
Rain        45.500000
Snow        26.333333
Name: Temperature, dtype: float64

In [116]:
#Aggregate multiple functions
grouped_agg=df.groupby('Events')['Temperature'].agg(['mean','sum','count'])
print(grouped_agg)

               mean  sum  count
Events
Fog-Snow  31.000000   62      2
Rain      45.500000  182      4
Snow      26.333333   79      3

In [119]:
# Merging and joining DataFrames
df1=pd.DataFrame({'key':['A','B','C','D'],'value':[1,2,3,4]})
df2=pd.DataFrame({'key':['B','D','A','F'],'value':[5,6,7,8]})

In [120]:
#Merging two dataframes
df3=pd.merge(df1,df2,on='key',how='inner')
print(df3)

  key  value_x  value_y
0   A        1        7
1   B        2        5
2   D        4        6

In [121]:
#Merging two dataframes
df3=pd.merge(df1,df2,on='key',how='outer')
print(df3)

  key  value_x  value_y
0   A      1.0      7.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      4.0      6.0
4   F      NaN      8.0

In [122]:
#Merging two dataframes
df3=pd.merge(df1,df2,on='key',how='left')
print(df3)

  key  value_x  value_y
0   A        1      7.0
1   B        2      5.0
2   C        3      NaN
3   D        4      6.0

In [124]:
#Merging two dataframes
df3=pd.merge(df1,df2,on='key',how='right')
print(df3)

  key  value_x  value_y
0   B      2.0        5
1   D      4.0        6
2   A      1.0        7
3   F      NaN        8